---

- name: Include secrets
  ansible.builtin.include_tasks: tasks/secrets.yml

- name: Create nginx config
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_items:
    - ../templates/openshift/nginx-configuration.yml

- name: Deploy nginx
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_items:
    - ../templates/openshift/nginx-deployment.yml


- name: Create service
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_items:
    - ../templates/openshift/nginx-service.yml

- name: Create route
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_items:
    - ../templates/openshift/nginx-route.yml

- name: Remove previous NginX deployments
  loop:
    - DeploymentConfig
    - Secret
    - ConfigMap
  vars:
    object_kind: '{{ item }}'
    label_selectors:
      - app={{ nginx_proxy_name }}
      - env={{ env }}
      - suffix!={{ suffix }}
  ansible.builtin.include_tasks: remove-objects.yml
