---
- name: Include community signing secrets
  ansible.builtin.include_tasks: tasks/community-signing-secrets.yml

- name: Deploy signing pipeline
  tags:
    - tekton-pipeline
    - community-signing
  kubernetes.core.k8s:
    state: present
    apply: true
    namespace: "{{ oc_namespace }}"
    definition: "{{ lookup('template', '{{ item }}') }}"
  with_items:
    - ../templates/openshift/pipelines/community-signing-pipeline.yml

- name: Include community signing event listener
  ansible.builtin.include_tasks: tasks/community-signing-event-listener.yml

- name: Include community signing trigger
  ansible.builtin.include_tasks: tasks/community-signing-trigger.yml
