---
- name: Configure Namespace
  tags:
    - namespace
    - init
  kubernetes.core.k8s:
    state: "present"
    definition:
      kind: Namespace
      apiVersion: v1
      metadata:
        name: "{{ oc_namespace }}"

- name: Create service account
  tags:
    - service-account
    - init
  kubernetes.core.k8s:
    state: present
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ service_account_name }}"

- name: Grant SA role "{{ service_account_name }}"
  tags:
    - service-account
    - init
  kubernetes.core.k8s:
    state: present
    namespace: "{{ oc_namespace }}"
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ service_account_name }}-{{ oc_namespace }}-{{ item }}"
      roleRef:
        kind: ClusterRole
        name: "{{ item }}"
      subjects:
        - kind: ServiceAccount
          name: "{{ service_account_name }}"
          namespace: "{{ oc_namespace }}"
  with_items:
    - cluster-admin
