---
nginx_proxy_image: registry.access.redhat.com/ubi9/nginx-120:1-46
nginx_proxy_replicas: 1

nginx_proxy_name: "nging-proxy"

nginx_proxy_log_dir: /logs
nginx_proxy_access_log_location: "{{ nginx_proxy_log_dir }}/nginx.access"
nginx_proxy_error_log_location: "{{ nginx_proxy_log_dir }}/nginx.error"
nginx_basic_user_file_local_path: /tmp/htpasswd  # noqa: var-naming[no-role-prefix]

nginx_basic_user_dir_path: /etc/nginx   # noqa: var-naming[no-role-prefix]
nginx_basic_user_file_path: /etc/nginx/htpasswd   # noqa: var-naming[no-role-prefix]
nginx_proxy_service_url: https://example.com   # noqa: var-naming[no-role-prefix]

nginx_port: 8080   # noqa: var-naming[no-role-prefix]

env: "none"   # noqa: var-naming[no-role-prefix]
suffix: "nginx"   # noqa: var-naming[no-role-prefix]
