---
name: validation

on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tox:
    name: Run unit tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install hadolint
          /home/linuxbrew/.linuxbrew/bin/brew install hadolint
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install hadolint
          /home/linuxbrew/.linuxbrew/bin/brew install hadolint
          sudo ln -s /home/linuxbrew/.linuxbrew/bin/hadolint /usr/bin/
          pdm sync -dG tox
          python3 -m pip install ansible-lint

      - name: Run Tests
        run: |
          pdm run -v tox
